default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog_ramos_development

test:
  <<: *default
  database: blog_ramos_test

production:
  primary: &primary_production
    <<: *default
    database: posts
    username: arthun01
    password: <%= ENV["BLOG_RAMOS_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: posts
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: posts
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: posts
    migrations_paths: db/cable_migrate
