default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog_ramos_development

test:
  <<: *default
  database: blog_ramos_test

production:
  <<: *default
  # use DATABASE_URL fornecido pelo Heroku (URL completa)
  url: <%= ENV['DATABASE_URL'] %>

# configuração específica para o Solid Cable (vai usar o mesmo DATABASE_URL por padrão)
cable:
  <<: *default
  url: <%= ENV['CABLE_DATABASE_URL'] || ENV['DATABASE_URL'] %>

queue:
  <<: *default
  url: <%= ENV['QUEUE_DATABASE_URL'] || ENV['DATABASE_URL'] %>
