default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog_ramos_development

test:
  <<: *default
  database: blog_ramos_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

# 🔧 Adicionando a configuração do banco para o Solid Cable
cable:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
