service: blog_ramos

image: arthun01/blog_ramos

servers:
  web:
    - 134.209.10.76

registry:
  username: arthun01
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
    - BLOG_RAMOS_DATABASE_PASSWORD
  clear:
    DB_HOST: localhost
    DB_NAME: posts
    DB_USER: arthun01

volumes:
  - blog_ramos_storage:/rails/storage
  - blog_ramos_pgdata:/var/lib/postgresql/data

asset_path: /rails/public/assets

builder:
  arch: amd64
